/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'ForgotPassword': RouteRecordInfo<
      'ForgotPassword',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'HrDashboard': RouteRecordInfo<
      'HrDashboard',
      '/hr-dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'MenuManager': RouteRecordInfo<
      'MenuManager',
      '/menu-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'OrderSummary': RouteRecordInfo<
      'OrderSummary',
      '/order-summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LoginPage': RouteRecordInfo<
      'LoginPage',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Register': RouteRecordInfo<
      'Register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'MyOrderHistory': RouteRecordInfo<
      'MyOrderHistory',
      '/my-order-history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'StaffDashboard': RouteRecordInfo<
      'StaffDashboard',
      '/staff-dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'WeeklyOverview': RouteRecordInfo<
      'WeeklyOverview',
      '/weekly-overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/ForgotPassword.vue': {
      routes:
        | 'ForgotPassword'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hr/HrDashboard.vue': {
      routes:
        | 'HrDashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hr/MenuManager.vue': {
      routes:
        | 'MenuManager'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hr/OrderSummary.vue': {
      routes:
        | 'OrderSummary'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/LoginPage.vue': {
      routes:
        | 'LoginPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Register.vue': {
      routes:
        | 'Register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/staff/MyOrderHistory.vue': {
      routes:
        | 'MyOrderHistory'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/staff/StaffDashboard.vue': {
      routes:
        | 'StaffDashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/staff/WeeklyOverview.vue': {
      routes:
        | 'WeeklyOverview'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
