/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'ForgotPassword': RouteRecordInfo<
      'ForgotPassword',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hr': RouteRecordInfo<
      '/hr',
      '/hr',
      Record<never, never>,
      Record<never, never>,
      | '/hr/'
      | '/hr/menu'
      | '/hr/orders'
    >,
    '/hr/': RouteRecordInfo<
      '/hr/',
      '/hr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hr/menu': RouteRecordInfo<
      '/hr/menu',
      '/hr/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hr/orders': RouteRecordInfo<
      '/hr/orders',
      '/hr/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Home': RouteRecordInfo<
      'Home',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'LoginPage': RouteRecordInfo<
      'LoginPage',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'Register': RouteRecordInfo<
      'Register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/staff': RouteRecordInfo<
      '/staff',
      '/staff',
      Record<never, never>,
      Record<never, never>,
      | '/staff/'
      | '/staff/history'
      | '/staff/overview'
    >,
    '/staff/': RouteRecordInfo<
      '/staff/',
      '/staff',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/staff/history': RouteRecordInfo<
      '/staff/history',
      '/staff/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/staff/overview': RouteRecordInfo<
      '/staff/overview',
      '/staff/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/forgot-password.vue': {
      routes:
        | 'ForgotPassword'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hr.vue': {
      routes:
        | '/hr'
        | '/hr/'
        | '/hr/menu'
        | '/hr/orders'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/hr/index.vue': {
      routes:
        | '/hr/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hr/menu.vue': {
      routes:
        | '/hr/menu'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hr/orders.vue': {
      routes:
        | '/hr/orders'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | 'Home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | 'LoginPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/Register.vue': {
      routes:
        | 'Register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/staff.vue': {
      routes:
        | '/staff'
        | '/staff/'
        | '/staff/history'
        | '/staff/overview'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/staff/index.vue': {
      routes:
        | '/staff/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/staff/history.vue': {
      routes:
        | '/staff/history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/staff/overview.vue': {
      routes:
        | '/staff/overview'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
